# Generated by Django 4.1.7 on 2023-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.IntegerField(verbose_name="Phone Number")),
                ("position", models.CharField(max_length=50, verbose_name="Position")),
                ("skills", models.TextField(verbose_name="Skills and Experience")),
                (
                    "image",
                    models.ImageField(default=None, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
