# Generated by Django 4.1.7 on 2023-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Developer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Phone Number"),
        ),
    ]
